### ISSUE TITLE
503 Errors when using `import_people`

### ISSUE THREAD

**Issue by gregwchase** [mixpanel/mixpanel-utils#23]
When sending a JSON object with the `import_people` method, the following errors are returned.

```
WARNING: The server couldn't fulfill the request.
WARNING: Error code: 503
WARNING: Reason: Service Unavailable
WARNING: Response: b'upstream connect error or disconnect/reset before headers'
WARNING: Attempting retry #1
WARNING: The server couldn't fulfill the request.
WARNING: Error code: 503
WARNING: Reason: Service Unavailable
WARNING: Response: b'upstream connect error or disconnect/reset before headers'
WARNING: Attempting retry #2
WARNING: The server couldn't fulfill the request.
WARNING: Error code: 503
WARNING: Reason: Service Unavailable
WARNING: Response: b'upstream connect error or disconnect/reset before headers'
WARNING: Attempting retry #1
WARNING: The server couldn't fulfill the request.
WARNING: Error code: 503
WARNING: Reason: Service Unavailable
WARNING: Response: b'upstream connect error or disconnect/reset before headers'
WARNING: Attempting retry #1
Exception in thread Thread-7:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 479, in _handle_results
cache[job]._set(i, obj)
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 649, in _set
self._callback(self._value)
File "/usr/local/lib/python3.6/site-packages/mixpanel_api/__init__.py", line 1268, in _response_handler_callback
response_data = json.loads(response)
File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
``` 

When debugging, each JSON object has the data in the correct format for Mixpanel, but the upload issue still persists.

**Comment by jaredmixpanel** [comment]
Appears to have been an upstream error. Please re-open with more detail if issue persists.
